[project]
name = "api"
version = "1.0.0"
description = ""
authors = ["Dawid Weglarz <dawid.weglarz95@gmail.com>"]
requires-python = ">=3.14"

dependencies = [
    "beautifulsoup4>=4.14.3",
    "flask-restful>=0.3.10",
    "flask>=3.1.2",
    "requests>=2.32.5",
    "waitress>=3.0.2",
]
